### PR TITLE
Add Support for Gamecontrollers with Presentation View

### LINKED ISSUE #10: Popup about time limit continuously opens
How to reproduce?

1. Set the maximal time a meeting can last to the lowest possible time.
2. Wait until the time is elapsed.

Expected behaviour: A single popup opens to indicate that the time has elapsed.

Observed behaviour: Each second the said popup opens.

Workaround: Press ESC to close all popups. Once all popups are closed no new popup opens.

Bug is in FindingsListFrame#updateClock. The flag should be set before displaying the popup.

### PR DESCRIPTION
**Pull request by googol42**
Hello,

this PR includes the work done in my thesis. This includes the following features:
1) A presentation view
2) Gamecontroller support to classify the findings and to provide feedback about the current meeting to the mdoerator
3) Auto completion for the reference field in the scribble view

To use the gamecontroller RevAger has to be started with ``java -Djava.library.path=. -jar <jar>`` and the files from ``lib/jinput-native-files/`` habe to be present in the working folder.

Current drawbacks:
- you have to pass the java library path manually
- the gamecontroller keys are hard coded

Other changes done:
- removed lots of useless (generated?) comments
- added Apache Commons Lang to simply String operations
- use lambdas
- convert attributes to local variables
- make attributes ``transistent``
- make use of generics
- lots of simplifications
- removed code without functionality
- removed commented code
- fixed #10 
- and more....

Sorry, that the diff is rather large.

### CODE REVIEW

**Comment by kuleszdl** [comment]
This sounds very nice, great job! @ibogicevic will review this in more detail and decide about acceptance.

But just out of curiosity: What's the issue behind not packaging the JAR and these jinput-files inside the RevAger archive?

**Comment by googol42** [comment]
The problem is, that you cannot access the files inside the JAR. The solution would be to save them to the tmp folder and set the path to the files via ``System.load(name)``.

**Comment by kuleszdl** [comment]
The solution as proposed here does not work?:

https://stackoverflow.com/questions/403256/how-do-i-read-a-resource-file-from-a-java-jar-file

**Comment by googol42** [comment]
The file must be present on the local file system. Solutions:
- https://github.com/adamheinrich/native-utils
- https://stackoverflow.com/questions/1611357/how-to-make-a-jar-file-that-includes-dll-files/1611367#1611367

These were not implemented/used by me, because I had already spent some time on this issue and eventually it was not a problem for my studies.

**Review by ibogicevic — APPROVED** [review]
Well implemented, very nice new features. Thanks!

**Pull request merged**
