### PR TITLE
Fix: remove dozens of warnings due to '_'-method

### PR DESCRIPTION
**Pull request by googol42**
_ should not be used as method name and causes dozens of warnings.

Conversion done with:

<pre>
find . -type f -name "*java*" -exec sed -i 's/_(/translate(/g' {} +
find . -type f -name "*java*" -exec sed -i 's/model.Data._/model.Data.translate/g' {} +</pre>

### CODE REVIEW

**Comment by kuleszdl** [comment]
Would this still work with automatic translations in launchpad and GNU Gettext? I mean, is the underscore not required there somehow?

**Comment by googol42** [comment]
The _ was the method name in the Data-class:
<pre>
	public static String _(String id) {
		/*
		 * Some special handling of the roles
		 */
		if (id.equals(Role.MODERATOR.toString())) {
			return _("Moderator");
		} else if (id.equals(Role.AUTHOR.toString())) {
			return _("Author");
		} else if (id.equals(Role.CUSTOMER.toString())) {
			return _("Customer");
		} else if (id.equals(Role.REVIEWER.toString())) {
			return _("Reviewer");
		} else if (id.equals(Role.SCRIBE.toString())) {
			return _("Scribe");
		}

		try {
			return langBundle.getString(id);
		} catch (Exception e) {
			/*
			 * If the string is not translated in the bundle, or the bundle
			 * cannot be found, just return the original string.
			 */
			return id;
		}
	}
</pre>
The actual translation is then done with langBundle#getString

**Comment by googol42** [comment]
I built this branch and all languages worked fine (tested in win vm)

**Comment by kuleszdl** [comment]
Okay, then I'm fine with accepting this. :+1:

**Pull request merged**
