### PR TITLE
Format Source Code using eclipse build-in formatters

### PR DESCRIPTION
**Pull request by googol42**
Run "Source -> {Format, Clean Up, Organize Imports}" in eclipse using the eclipse build-in formatters. No manual changes.

Better do this once and in one PR, instead of having formatting changes in commits with real changes.

### CODE REVIEW

**Comment by googol42** [comment]
@kuleszdl could you review this?

**Comment by kuleszdl** [comment]
@googol42 ~230 changed files - are you serious? :) Dunno how to review this the best way, I'll ask one of the others for help.

**Comment by googol42** [comment]
@kuleszdl they are all auto-generated by eclipse. Better have these changes in one commit than regular mixed up with logical changes.

Most of them are joined lines, replace spaces by tabs (as most of the files used tabs), removed unused imports...

**Comment by kuleszdl** [comment]
I looked over them and it looks fine at first sight. Since we don't have a stable master branch I guess we can just include them.

What would be nice (future work in separate ticket): We could integrate checkstyle or a similar tool in our build process so we will recognize code-style issues as soon as they arise.

**Pull request merged**
